# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

em_normal_partial_concordant_cpp <- function(x, y, zxy, n, pi, mu, sigma, nu, tau, g, loglik, tol, restriction, constrain, iteration, convergence) {
    .Call(`_discordant_em_normal_partial_concordant_cpp`, x, y, zxy, n, pi, mu, sigma, nu, tau, g, loglik, tol, restriction, constrain, iteration, convergence)
}

subsampling_cpp <- function(x, y, zxy, n, pi, mu, sigma, nu, tau, g) {
    .Call(`_discordant_subsampling_cpp`, x, y, zxy, n, pi, mu, sigma, nu, tau, g)
}

